import colours from 'tailwindcss/colors';

enum Nation {
  Ankara = 'Ankara',
  Belgium = 'Belgium',
  Berlin = 'Berlin',
  Brest = 'Brest',
  Budapest = 'Budapest',
  Bulgaria = 'Bulgaria',
  Constantinople = 'Constantinople',
  Denmark = 'Denmark',
  Edinburgh = 'Edinburgh',
  Greece = 'Greece',
  Holland = 'Holland',
  Kiel = 'Kiel',
  London = 'London',
  Liverpool = 'Liverpool',
  Marseille = 'Marseille',
  Moscow = 'Moscow',
  Munich = 'Munich',
  Naples = 'Naples',
  Norway = 'Norway',
  Paris = 'Paris',
  Portugal = 'Portugal',
  Rome = 'Rome',
  Rumania = 'Rumania',
  Serbia = 'Serbia',
  Sevastopol = 'Sevastopol',
  Smyrna = 'Smyrna',
  Spain = 'Spain',
  StPetersburg = 'StPetersburg',
  Sweden = 'Sweden',
  Trieste = 'Trieste',
  Tunis = 'Tunis',
  Venice = 'Venice',
  Vienna = 'Vienna',
  Warsaw = 'Warsaw'
}

export const getNationColour = (nation?: Nation, isEmphasised: boolean = true) => {
  if (!nation) return colours.orange[isEmphasised ? 300 : 200];
  return {
    [Nation.Ankara]: '#5D8AA8',
    [Nation.Belgium]: '#FF1717',
    [Nation.Berlin]: '#BF367E',
    [Nation.Brest]: '#ED3CCA',
    [Nation.Budapest]: '#89CFF0',
    [Nation.Bulgaria]: '#223241',
    [Nation.Constantinople]: '#A4C639',
    [Nation.Denmark]: '#CAB310',
    [Nation.Edinburgh]: '#4B5320',
    [Nation.Greece]: '#FD5F00',
    [Nation.Holland]: '#B2BEB5',
    [Nation.Kiel]: '#1ADD51',
    [Nation.London]: '#00FFFF',
    [Nation.Liverpool]: '#FF9966',
    [Nation.Marseille]: '#FDEE00',
    [Nation.Moscow]: '#C072C8',
    [Nation.Munich]: '#A08A75',
    [Nation.Naples]: '#004225',
    [Nation.Norway]: '#4D4DC5',
    [Nation.Paris]: '#87A96B',
    [Nation.Portugal]: '#5CFF9B',
    [Nation.Rome]: '#FA9D71',
    [Nation.Rumania]: '#FFF984',
    [Nation.Serbia]: '#CFEB1E',
    [Nation.Sevastopol]: '#46B300',
    [Nation.Smyrna]: '#FFBF00',
    [Nation.Spain]: '#93A2D0',
    [Nation.StPetersburg]: '#8B0000',
    [Nation.Sweden]: '#ACE1AF',
    [Nation.Trieste]: '#007FFF',
    [Nation.Tunis]: '#FBCCE7',
    [Nation.Venice]: '#6B3F95',
    [Nation.Vienna]: '#FF8C00',
    [Nation.Warsaw]: '#00CC99',
  }[nation];
};

export default Nation;
